//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarudoSDK.Generated
{
    using UMod.Shared;
    
    
    public class ModToolsMenu
    {
        
        [UnityEditor.MenuItem("Warudo/New Mod", priority=0)]
        internal static void Menu_New_Mod()
        {
            UMod.BuildEngine.ModToolsUtil.ShowToolsWindow(typeof(UMod.Exporter.CreateModWindow));
        }
        
        [UnityEditor.MenuItem("Warudo/Switch Active Mod...", priority=21)]
        internal static void Menu_Switch_Active_Mod___()
        {
            UMod.BuildEngine.ModToolsUtil.ShowToolsWindow(typeof(UMod.Exporter.ExporterWindow));
        }
        
        [UnityEditor.MenuItem("Warudo/Setup Character...", priority=42)]
        internal static void Menu_Setup_Character___()
        {
            UMod.BuildEngine.ModToolsUtil.ShowToolsWindow(typeof(Warudo.Editor.SetupCharacterWindow));
        }
        
        [UnityEditor.MenuItem("Warudo/Mod Settings", priority=43)]
        internal static void Menu_Mod_Settings()
        {
            UMod.BuildEngine.ModToolsUtil.ShowToolsWindow(typeof(UMod.Exporter.SettingsWindow));
        }
        
        [UnityEditor.MenuItem("Warudo/Build Mod %#b", priority=44)]
        internal static void Menu_Build_Mod___b()
        {
            UMod.ModTools.Export.ExportSettings settings = UMod.ModTools.Export.ExportSettings.Active.Load();
            if ((settings == null))
            {
                throw new UMod.ModLoadException("The export settings are missing from this mod tools package");
            }
            UMod.BuildEngine.ModToolsUtil.StartBuild(settings);
        }
    }
}
